# Generated by Django 6.0.4 on 2026-04-07 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(unique=True)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cedula'), ('CE', 'Cedula extranjeria'), ('TI', 'Tarjeta identidad'), ('PAS', 'Pasaporte')], max_length=5)),
                ('numero_documento', models.CharField(max_length=30, unique=True)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('edad', models.PositiveSmallIntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('direccion', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('tipo_usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AcudienteMinor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.usuario')),
            ],
            bases=('api.usuario',),
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.usuario')),
            ],
            bases=('api.usuario',),
        ),
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.usuario')),
            ],
            bases=('api.usuario',),
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.usuario')),
                ('puntos_experiencia', models.IntegerField(default=0)),
            ],
            bases=('api.usuario',),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.usuario')),
            ],
            bases=('api.usuario',),
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clasificacion_esrb', models.CharField(max_length=10)),
                ('desarrollador', models.CharField(max_length=100)),
                ('numero_jugadores', models.IntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('existencias', models.IntegerField()),
                ('plataformas', models.ManyToManyField(related_name='juegos', to='api.plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plataforma')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('total_existentes', models.IntegerField()),
                ('ip', models.GenericIPAddressField()),
                ('mac_lan', models.CharField(max_length=50)),
                ('mac_wifi', models.CharField(max_length=50)),
                ('total_controles', models.IntegerField()),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plataforma')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(max_length=50)),
                ('usuario_red', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes', to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Trofeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puntos', models.IntegerField()),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.juego')),
                ('usuarios', models.ManyToManyField(blank=True, related_name='trofeos', to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('horas_juego', models.IntegerField(default=0)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.juego')),
                ('trofeos', models.ManyToManyField(blank=True, related_name='equipos', to='api.trofeo')),
                ('usuarios', models.ManyToManyField(related_name='equipos', to='api.atleta')),
            ],
        ),
        migrations.CreateModel(
            name='SesionEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(max_length=20)),
                ('puntos_experiencia', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.equipojuego')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.juego')),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.arbitro')),
                ('atleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.atleta')),
            ],
        ),
    ]
