# Generated by Django 6.0.4 on 2026-04-08 02:11

import api.models.usuario
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(blank=True, default=api.models.usuario.generar_codigo_unico, max_length=50, null=True, unique=True),
        ),
    ]
