# Generated by Django 6.0.4 on 2026-04-08 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuario_codigo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquipoJuego',
            new_name='Equipo',
        ),
    ]
