# Generated by Django 6.0.4 on 2026-04-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_equipojuego_equipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='horas_juego',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='juego',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='trofeos',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='usuarios',
        ),
        migrations.RemoveField(
            model_name='sesionentrenamiento',
            name='arbitro',
        ),
        migrations.RemoveField(
            model_name='sesionentrenamiento',
            name='atleta',
        ),
        migrations.RemoveField(
            model_name='sesionentrenamiento',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='sesionentrenamiento',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='sesionentrenamiento',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='sesionentrenamiento',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='sesionentrenamiento',
            name='juego',
        ),
        migrations.RemoveField(
            model_name='sesionentrenamiento',
            name='puntos_experiencia',
        ),
        migrations.AddField(
            model_name='equipo',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sesionentrenamiento',
            name='hora_inicio_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesionentrenamiento',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sesionentrenamiento',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('en curso', 'En Curso'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='programada', max_length=20),
        ),
    ]
