# Generated by Django 5.2.12 on 2026-03-23 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(unique=True, verbose_name='Codigo')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cedula'), ('CE', 'Cedula extranjeria'), ('TI', 'Tarjeta identidad'), ('PAS', 'Pasaporte')], max_length=5, verbose_name='Tipo documento')),
                ('numero_documento', models.CharField(max_length=30, unique=True, verbose_name='Numero documento')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('edad', models.PositiveSmallIntegerField(verbose_name='Edad')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, verbose_name='Numero')),
                ('tipo', models.CharField(choices=[('movil', 'Movil'), ('fijo', 'Fijo'), ('trabajo', 'Trabajo')], max_length=10, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Telefono',
                'verbose_name_plural': 'Telefonos',
                'ordering': ['id'],
            },
        ),
    ]
