# Generated by Django 5.2.12 on 2026-03-27 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcudienteMinor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuario')),
            ],
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuario')),
            ],
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuario')),
            ],
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('puntos_experiencia', models.IntegerField(default=0)),
            ],
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clasificacion_esrb', models.CharField(max_length=10)),
                ('desarrollador', models.CharField(max_length=100)),
                ('numero_jugadores', models.IntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('existencias', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuario')),
            ],
            bases=('usuarios.usuario',),
        ),
        migrations.AlterModelOptions(
            name='telefono',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.RemoveField(
            model_name='telefono',
            name='created_at',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='numero',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='tipo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_documento',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cedula'), ('CE', 'Cedula extranjeria'), ('TI', 'Tarjeta identidad'), ('PAS', 'Pasaporte')], max_length=5),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='EquipoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('horas_juego', models.IntegerField(default=0)),
                ('usuarios', models.ManyToManyField(related_name='equipos', to='usuarios.atleta')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.juego')),
            ],
        ),
        migrations.AddField(
            model_name='juego',
            name='plataformas',
            field=models.ManyToManyField(related_name='juegos', to='usuarios.plataforma'),
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.plataforma')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('total_existentes', models.IntegerField()),
                ('ip', models.GenericIPAddressField()),
                ('mac_lan', models.CharField(max_length=50)),
                ('mac_wifi', models.CharField(max_length=50)),
                ('total_controles', models.IntegerField()),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.plataforma')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(max_length=50)),
                ('usuario_red', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='SesionEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(max_length=20)),
                ('puntos_experiencia', models.IntegerField(default=0)),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.arbitro')),
                ('atleta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.atleta')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.equipojuego')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.juego')),
            ],
        ),
        migrations.CreateModel(
            name='Trofeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('puntos', models.IntegerField()),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.juego')),
                ('usuarios', models.ManyToManyField(blank=True, related_name='trofeos', to='usuarios.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='equipojuego',
            name='trofeos',
            field=models.ManyToManyField(blank=True, related_name='equipos', to='usuarios.trofeo'),
        ),
    ]
